#!/bin/bash



RED='\033[31m'
RESET='\033[0m'
CHOICE=-1



function show_language_menu() {
    clear

    echo -e "${RED}"
    echo " ____       _     _              ____             __ "
    echo "|  _ \\  ___| |__ (_) __ _ _ __  / ___|___  _ __  / _|"
    echo "| | | |/ _ \\ '_ \\| |/ _\` | '_ \\| |   / _ \\| '_ \\| |_ "
    echo "| |_| |  __/ |_) | | (_| | | | | |__| (_) | | | |  _|"
    echo "|____/ \\___|_.__/|_|\\__,_|_| |_|\\____\\___/|_| |_|_|  "
    echo -e "${RESET}"

    echo "Choose your language:"
    echo "1. Português"
    echo "2. English"
}



until [[ $choice -ge 0 && $choice -le 2 ]]; do
    show_language_menu
    read -p "Your choice: " choice
done