#!/bin/bash



function choose_graphical_interface_en() {
    CHOICE=-1

    until [[ $CHOICE -ge 1 && $CHOICE -le 6 ]]; do
        clear 

        echo "Choose your graphical interface style:"
        echo "1. GNOME Dark"
        echo "2. GNOME Light"
        echo "3. macOS Style"
        echo "4. Windows Style"
        echo "5. Retro Style"
        echo "6. List Packages"
        echo "7. Back to menu"

        read -p "Your choice (1-7): " CHOICE
    done

    case $CHOICE in
        1) gnome_dark ;;
        2) gnome_light ;;
        3) macOS ;;
        4) windows ;;
        5) retro ;;
        6) list_packages ;;
        7) break;;
        *) echo "Invalid choice. Please select a number between 1 and 5." ;;
    esac
}



function gnome_dark() {
    sudo apt update -y
    sudo apt install -y gnome-tweaks gnome-shell-extensions papirus-icon-theme

    gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
    gsettings set org.gnome.desktop.interface icon-theme "Papirus"
    gsettings set org.gnome.desktop.interface cursor-theme "Adwaita"

    echo "Gnome Dark theme applied successfully!"
}



function gnome_light() {
    sudo apt update -y
    sudo apt install -y gnome-tweaks gnome-shell-extensions papirus-icon-theme

    gsettings set org.gnome.desktop.interface gtk-theme "Adwaita"
    gsettings set org.gnome.desktop.interface icon-theme "Papirus"
    gsettings set org.gnome.desktop.interface cursor-theme "Adwaita"
    
    echo "Gnome Light theme applied successfully!"
}



function macOS() {
    sudo apt update -y
    sudo apt install -y gnome-tweaks gnome-shell-extensions

    mkdir -p ~/.themes
    cd ~/.themes
    git clone https://github.com/vinceliuice/WhiteSur-gtk-theme.git WhiteSur
    cd WhiteSur
    ./install.sh

    mkdir -p ~/.icons
    cd ~/.icons
    git clone https://github.com/vinceliuice/WhiteSur-icon-theme.git WhiteSur

    gsettings set org.gnome.desktop.interface gtk-theme "WhiteSur"
    gsettings set org.gnome.desktop.interface icon-theme "WhiteSur"
    gsettings set org.gnome.desktop.interface cursor-theme "WhiteSur"

    echo "MacOS style theme applied successfully!"
}



function windows() {
    sudo apt update -y
    sudo apt install -y gnome-tweaks gnome-shell-extensions

    mkdir -p ~/.themes
    cd ~/.themes
    git clone https://github.com/B00merang-Project/Windows-10 Windows10

    mkdir -p ~/.icons
    cd ~/.icons
    git clone https://github.com/B00merang-Project/Windows-10-Icons.git Windows10

    gsettings set org.gnome.desktop.interface gtk-theme "Windows10"
    gsettings set org.gnome.desktop.interface icon-theme "Windows10"
    gsettings set org.gnome.desktop.interface cursor-theme "Windows10"

    echo "Windows style theme applied successfully!"
}



function retro() {
    sudo apt update -y
    sudo apt install -y gnome-tweaks gnome-shell-extensions numix-icon-theme

    mkdir -p ~/.themes
    cd ~/.themes
    git clone https://github.com/adapta-project/adapta-gtk-theme.git Adapta
    cd Adapta
    ./autogen.sh --prefix=/usr
    sudo make install

    gsettings set org.gnome.desktop.interface gtk-theme "Adapta"
    gsettings set org.gnome.desktop.interface icon-theme "Numix"
    gsettings set org.gnome.desktop.interface cursor-theme "Adwaita"

    echo "Retro style theme applied successfully!"
}
