#!/bin/bash



function confauth() {
    #
    # Configuring backups.
    #
    configure_automatic_backup

    #
    # Configuring network.
    #
    configure_network_interfaces
    configure_dns
    restart_network_services

    #
    # Configuring packages manager.
    #
    configure_apt_preferences
    set_up_aptitude
    configure_package_caching
    configure_automatic_upgrades
    install_package_management_tools

    #
    # Configuring System.
    #
    install_and_configure_software
    detect_and_install_video_drivers
    optimize_cpu_performance
    configure_ram_and_ssd
    configure_power_settings
    update_firmware
    manage_device_drivers
    optimize_temp_files
    install_diagnostic_tools

    #
    # Configuring Audio.
    #
    adjust_volume
    adjust_balance
    set_input_device
    set_output_device
    configure_audio_profile
    install_audio_tools

    #
    # Configuring Security.
    #
    configure_firewall
    harden_ssh
    install_configure_fail2ban
    install_configure_apparmor
    configure_auditd
    apply_kernel_security
    configure_ssh_rate_limiting
    install_configure_clamav
    block_unused_ports
    install_configure_rkhunter
    configure_fail2ban_for_services
    enforce_password_policy
    install_configure_aide
    configure_logrotate
}



function configure_automatic_backup() {
    echo "Setting up automatic backup."

    SOURCE_DIR="$HOME"
    BACKUP_BASE_DIR="$HOME/Backups"
    
    mkdir -p "$BACKUP_BASE_DIR"

    CRON_JOB="0 2 1 * * mkdir -p \$HOME/Backups/\$(date +\%Y)/\$(date +\%B) && rsync -avh --delete --exclude='\Backups' \$HOME/ \$HOME/Backups/\$(date +\%Y)/\$(date +\%B)/"

    (crontab -l; echo "$CRON_JOB") | crontab -

    echo "Automatic backup configured."
}



function configure_network_interfaces() {
    echo "Configuring all network interfaces..."

    INTERFACES=$(ip link show | awk '/^[0-9]+:/{print $2}' | sed 's/://')

    for INTERFACE in $INTERFACES; do
        echo "Configuring interface: $INTERFACE"
        sudo ip link set "$INTERFACE" up

        if ip link show "$INTERFACE" | grep -q 'ether'; then
            echo "$INTERFACE is an Ethernet interface."
            configure_dhcp "$INTERFACE"
        elif ip link show "$INTERFACE" | grep -q 'wl\|wlan'; then
            echo "$INTERFACE is a Wi-Fi interface."
            configure_dhcp "$INTERFACE"
        else
            echo "$INTERFACE is of unknown type."
        fi
    done
}



function configure_dhcp() {
    INTERFACE=$1

    echo "Configuring DHCP on $INTERFACE..."

    sudo ip addr flush dev "$INTERFACE"
    sudo ip route flush dev "$INTERFACE"
    sudo dhclient "$INTERFACE"

    echo "DHCP configuration applied to the $INTERFACE interface."
}



function configure_dns() {
    echo "Configuring DNS servers..."

    DNS1="1.1.1.1"
    DNS2="1.0.0.1"

    echo "nameserver $DNS1" | sudo tee /etc/resolv.conf > /dev/null
    echo "nameserver $DNS2" | sudo tee -a /etc/resolv.conf > /dev/null

    echo "DNS configuration applied: $DNS1 ${DNS2:+and $DNS2}"
}



function restart_network_services() {
    echo "Restarting network services..."

    sudo systemctl restart networking
    sudo systemctl restart NetworkManager

    echo "Network services restarted."
}



function configure_apt_preferences() {
    echo "Configuring APT preferences..."

    sudo mkdir -p /etc/apt/preferences.d

    echo "Package: *" | sudo tee /etc/apt/preferences.d/custom.pref > /dev/null
    echo "Pin: release a=stable" | sudo tee -a /etc/apt/preferences.d/custom.pref > /dev/null
    echo "Pin-Priority: 500" | sudo tee -a /etc/apt/preferences.d/custom.pref > /dev/null
    
    echo "APT preferences configured."
}



function set_up_aptitude() {
    echo "Configuring Aptitude..."

    sudo apt install -y aptitude

    echo "Aptitude installed and configured."
}



function configure_package_caching() {
    echo "Configuring package caching..."
    echo "Configuring APT cache directories..."
    
    sudo mkdir -p /var/cache/apt/archives/partial
    sudo chmod 755 /var/cache/apt/archives/partial

    echo "Configuring APT cache clearing..."
    echo "APT::Clean-Installed \"true\";" | sudo tee /etc/apt/apt.conf.d/10clean > /dev/null

    echo "Packet cache configured."
}



function configure_automatic_upgrades() {
    echo "Configuring automatic updates..."

    echo "Installing unattended-upgrades..."

    sudo apt install -y unattended-upgrades

    echo "Configuring unattended-upgrades..."

    sudo dpkg-reconfigure --priority=low unattended-upgrades

    echo "Automatic updates configured."
}
