#!/bin/bash



function setup() {
    local lang=$1

    if [ "$lang" = "PT" ]; then
        setup_pt
    else
        setup_en
    fi
}



function setup_pt() {
    local options=(
        "Configurar a Interface Gráfica"
        "Configurar o Som e o Áudio"
        "Configurar a Rede"
        "Configurar o Sistema e Hardware"
        "Configurar os Pacotes"
        "Configurar Sistemas de Segurança"
        "Configurar Backup"
        "Configurar tudo Automaticamente"
        "Sair"
    )
}