#!/bin/bash



source "src/core/en/gui"
source "src/core/pt/gui"
source "src/core/en/csc"
source "src/core/pt/csc"
source "src/core/en/cnt"
source "src/core/pt/cnt"
source "src/core/en/cs"



SELECTED_OPTION=-1



function setup() {
    local lang=$1

    if [ "$lang" = "PT" ]; then
        setup_pt
    else
        setup_en
    fi
}



function show_menu() {
    local options=("$@")
    local choice=0
    local input

    while true; do
        #clear
        
        for i in "${!options[@]}"; do
            if [ $i -eq $choice ]; then
                echo -e "> ${options[$i]} <"
            else
                echo "  ${options[$i]}"
            fi
        done

        read -rsn1 input

        case $input in
            $'\x1b')
                read -rsn2 input
                case $input in
                    '[A')
                        ((choice--))
                        if [ $choice -lt 0 ]; then
                            choice=$((${#options[@]} - 1))
                        fi
                        ;;
                    '[B')
                        ((choice++))
                        if [ $choice -ge ${#options[@]} ]; then
                            choice=0
                        fi
                        ;;
                esac
                ;;
            '')
                SELECTED_OPTION=$choice
                return
                ;;
            *)
                echo "Invalid input. Use arrow keys to navigate and Enter to select."
                ;;
        esac
    done
}



function setup_pt() {
    local options=(
        "Configurar a Interface Gráfica"
        "Configurar o Som e o Áudio"
        "Configurar a Rede"
        "Configurar o Sistema e Hardware"
        "Configurar os Pacotes"
        "Configurar Sistemas de Segurança"
        "Configurar Backup"
        "Configurar tudo Automaticamente"
        "Sair"
    )

    while true; do
        show_menu "${options[@]}"
        
        case "$SELECTED_OPTION" in 
            0) choose_graphical_interface_pt ;;
            1) choose_sound_configuration_pt ;;
            2) configure_network_pt ;;
            3) echo "Configurar o Sistema e Hardware" ;;
            4) echo "Configurar os Pacotes" ;;
            5) echo "Configurar Sistemas de Segurança" ;;
            6) echo "Configurar Backup" ;;
            7) echo "Configurar tudo Automaticamente" ;;
            8) 
                clear
                echo -e "${RED}"
                
                echo "__  __             "
                echo "\\ \/ /__ _ _   _  "
                echo " \  // _\` | | | | "
                echo " /  \\ (_| | |_| | "
                echo "/_/\\_\\__,_|\__,_|"
                
                exit 0 ;;
            *) echo "Opção inválida. Tente novamente." ;;
        esac
    done 
}



function setup_en() {
    local options=(
        "Configuring the Graphical Interface"
        "Configuring Sound and Audio"
        "Setting up the network"
        "Configuring the System and Hardware"
        "Configuring Packages"
        "Configuring Security Systems"
        "Configure Backup"
        "Configure everything Automatically"
        "Exit"
    )

    while true; do
        show_menu "${options[@]}"
        
        case "$SELECTED_OPTION" in 
            0) choose_graphical_interface_en ;;
            1) choose_sound_configuration_en ;;
            2) configure_network_en ;;
            3) echo "Configuring the System and Hardware" ;;
            4) echo "Configuring Packages" ;;
            5) echo "Configuring Security Systems" ;;
            6) echo "Configure Backup" ;;
            7) echo "Configure everything Automatically" ;;
            8) 
                clear
                echo -e "${RED}"
                
                printf " ____              \n"
                printf "| __ ) _   _  ___  \n"
                printf "|  _ \| | | |/ _ \ \n"
                printf "| |_) | |_| |  __/ \n"
                printf "|____/ \__, |\___| \n"
                printf "       |___/       \n"
                
                exit 0 ;;
            *) echo "Invalid option. Please try again." ;;
        esac
    done 
}